version: '3'
services:
  
  lb:
    image: nginx
    ports:
      - 80:80
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - app1
      - app2
      - db
    restart: on-failure
        
  app1:
    build: .
    ports:
      - 8081:8080
    environment:
      - JAVA_OPTS=-server -Djava.net.preferIPv4Stack=true
    depends_on: 
      - db
    restart: on-failure
    
  app2:
    build: .
    ports:
      - 8082:8080
    environment:
      - JAVA_OPTS=-server -Djava.net.preferIPv4Stack=true
    depends_on: 
      - db
    restart: on-failure
    
  app3:
    build: .
    ports:
      - 8083:8080
    environment:
      - JAVA_OPTS=-server -Djava.net.preferIPv4Stack=true
    depends_on: 
      - db
    restart: on-failure
    
  db:
    image: mysql:5.6
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app*1234